import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header'
import GeneralInformation from '@/Components/GeneralInformation'
import Services from '@/Components/Services'
import Projects from '@/Components/ProjectsSection'
import Contact from '@/Components/Contact'
import NavBar from '@/Components/NavBar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Cchang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={styles.main}>
        <Header />
        <NavBar />
        <div className="desktopView">
          <GeneralInformation />
          <div className="desktopView rightColumn">
            <Services />
            <div>
              <Projects />
              <Contact />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
