import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header'
import GeneralInformation from '@/Components/GeneralInformation'
import Services from '@/Components/Services'
import Projects from '@/Components/Projects'
import Contact from '@/Components/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <GeneralInformation />
        <Services />
        <Projects />
        <Contact />
      </main>
    </>
  )
}
